package io.github.fourfantastics.standby.model;

public enum RoleType {
	ACTOR,SCREENWRITER,DIRECTOR,ANIMATOR,SOUNTRACKCOMPOSER,PRODUCER,MAKEUPARTIST,
   CAMERA,COSTUMEDESIGNER,SOUNDTECHNICIAN,EDITOR,CINEMATOGRAPHER,GAFFER,OTHER
}
